#!/bin/bash
e="\x1b[";
c=$e"39;49;00m";
y=$e"93;01m";
cy=$e"96;01m";
r=$e"1;91m";
g=$e"92;01m";
abort() { cd "$PWD"; echo " "; echo -e "$cy >>$c$r Exit script$c\n"; }
###########################################################
bin="$PWD/.bin";
chmod -R 755 "$bin"/*;
cd "$PWD";
unpackbootimg=$bin/unpackbootimg;
###########################################################
clear;
###########################################################
if [ ! "$1" ]; 
	then
	echo -e "$r Файл не выбран. Ошибка!$c";
	abort;
	exit 1;
fi;
if [ ! "$2" ]; 
	then
	echo -e "$r Нет папки для распаковки. Ошибка!$c";
	abort;
	exit 1;
fi;
###########################################################
file=$(basename "$1");
origfile=$(basename "$2");
filename="${origfile%.*}";
echo -e "Ваш образ $y $origfile$c";
###########################################################
echo " ";
wimage="$file";
###########################################################
if [[ "$wimage" = "boot.img" ]];
	then
	if [ -f boot.img ];
		then		
		if [ "$file" == boot.img ];
			then
			cp -f boot.img bckp-boot.img;
			else
			mv -f boot.img bckp-boot.img;
			cp -f "$file" bckp-"$file";
			mv -f "$file" boot.img;
		fi;
		else
		cp -f "$file" bckp-"$file";
		mv -f "$file" boot.img;
	fi;
	if [[ $filename != *boot* ]];
	then
	  filename=boot-"$filename";
	fi;
fi;
###########################################################
if [ -d "$filename" ];
	then
	rm -rf "$filename";
fi;
mkdir -p "$filename";
chmod 777 "$filename";
###########################################################
if [[ -z "$wimage" ]];
	then
	echo -e "$r Нет файла. Ошибка!$c";
	abort;
	exit 1;
fi;
echo " ";
if [ ! "$3" ];
	then
	$unpackbootimg -i "$wimage" -o "$filename";
	else
	$unpackbootimg -i "$wimage" -o "$filename" --mtk 1;
fi;
if [[ "$wimage" = "boot.img" ]];
	then
	rm -f boot.img;
	if [ "$file" == boot.img ];
		then
		mv -f bckp-boot.img boot.img;
		else
		if [ -f bckp-boot.img ];
			then
			mv -f bckp-boot.img boot.img;
			mv -f bckp-"$file" "$file";
			else
			mv -f bckp-"$file" "$file";
		fi;		
	fi;		
fi;
cd "$filename";
comprfile=$(find . -name "*-ramdisk.*");
compress="${comprfile##*.}";
filecomp="$wimage"-ramdisk-compress;
if [ ! -f "$filecomp" ]
	then 
	echo "$compress" > "$filecomp" ;
fi;
mkdir -p ramdisk;
###########################################################
cd ramdisk;
###########################################################
if [ "$compress" == "gz" ];
	then
	gzip -dcv "../$wimage-ramdisk.gz" | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.gz";
	cd ../ ;
fi;
if [ "$compress" == "lzma" ];
	then
	xz -dcv "../$wimage-ramdisk.lzma" | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.lzma";
	cd ../ ;
fi;
if [ "$compress" == "xz" ];
	then
	xz -dcv "../$wimage-ramdisk.xz" | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.xz";
	cd ../ ;
fi;
if [ "$compress" == "bz2" ];
	then
	bzip2 -dcv "../$wimage-ramdisk.bz2" | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.bz2";
	cd ../ ;
fi;
if [ "$compress" == "lzo" ];
	then
	lzop -dcv "../$wimage-ramdisk.lzo" | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.lzo";
	cd ../ ;
fi;
if [ "$compress" == "lz4" ];
	then
	lz4 -dv "../$wimage-ramdisk.lz4" stdout | cpio -i ;
	if [ ! $? -eq "0" ]; 
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Ошибка!$c";
	  abort;
	  exit 1;
	fi;
	cd ../ ;
	rm -f "$wimage-ramdisk.lz4";
	cd ../ ;
fi;
if [ "$compress" == "unknown" ];
	then
	  echo -e "$r Ваш рамдиск повреждён или запакован не поддерживаемым форматом. Проинформируйте автора для поиска решения этой проблемы.$c";
	  abort;
	  exit 1;
fi;
echo " ";
###########################################################
echo -e "Готово! Ваш образ перепакован в $y $filename$c.";
echo " ";
